apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlens-ingress
  namespace: mlens
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mlens.fr
        - www.mlens.fr
      secretName: mlens-tls
  rules:
    - host: mlens.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: www.mlens.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
